New-ADUser -Name "Justin Sandy" `
           -GivenName "Justin" `
           -Surname "Sandy" `
           -SamAccountName "justin.sandy" `
           -UserPrincipalName "justin@DC300151403-00.local" `
           -AccountPassword (ConvertTo-SecureString "MotDePasse123@" -AsPlainText -Force) `
           -Enabled $true `
           -Path "CN=Users,DC=DC300151403-00,DC=local" `
           -Credential $credNew-ADUser -Name "Justin Sandy" `
           -GivenName "Justin" `
           -Surname "Sandy" `
           -SamAccountName "justin.sandy" `
           -UserPrincipalName "justin@DC300151403-00.local" `
           -AccountPassword (ConvertTo-SecureString "MotDePasse123@" -AsPlainText -Force) `
           -Enabled $true `
           -Path "CN=Users,DC=DC300151403-00,DC=local" `
           -Credential $cred
